### PR TITLE
enable mounting ES data directory to docker host

### PR DESCRIPTION
**Pull request by benjamin-smith**
Would be nice to be able to persist ES/Logstash data between restarts.

### CODE REVIEW

**Comment by spirosoik** [comment]
I agree with @benjamin-smith ! :+1:  @deviantony  @benjamin-smith is right for that. there is no way to keep the data otherwise.

**Comment by deviantony** [comment]
Oops, sorry for the late. 

Thanks @benjamin-smith @spirosoik

**Comment by spirosoik** [comment]
:+1: thanks @deviantony

**Comment by benjamin-smith** [comment]
Thanks @deviantony!

**Pull request merged**
